## 이원배치분산분석(Two-Way)
- 두 개의 독립 변수가 종속 변수에 미치는 영향을 분석하는 통계 기법

In [2]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("../data/funda_sampling.csv",index_col=0)

In [20]:
import statsmodels.api as sm
import pandas as pd
from statsmodels.formula.api import ols

# 데이터 불러오기
data = df[["region","type_of_business","amount"]]

## Two-way ANOVA에 맞는 수식을 설정하는 코드
two_way_anova = ols('amount ~ C(region) + C(type_of_business) + C(region):C(type_of_business)'
           , data = data).fit()
 
## 결과 해석을 저장하는 코드
result = sm.stats.anova_lm(two_way_anova)
 
## 결과 요약
print(result)

                                   df        sum_sq       mean_sq          F  \
C(region)                         9.0  2.658878e+10  2.954309e+09   9.551069
C(type_of_business)               9.0  8.496229e+10  9.440254e+09  30.519667
C(region):C(type_of_business)    81.0  5.931516e+10  7.322860e+08   2.367428
Residual                       6207.0  1.919931e+12  3.093171e+08        NaN

                                     PR(>F)
C(region)                      1.346181e-14
C(type_of_business)            9.993800e-53
C(region):C(type_of_business)  9.414117e-11
Residual                                NaN

In [21]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
# Tukey's HSD 사후검정 수행
# `pairwise_tukeyhsd`는 단일 범주형 변수에 대해 수행
# 이를 위해 'amount'를 'region'별로 구분하여 분석

tukey = pairwise_tukeyhsd(endog=data['amount'], groups=data['region'], alpha=0.05)

# Tukey's HSD 결과 출력
print("\nTukey's HSD 사후검정 결과:")
print(tukey)

Tukey's HSD 사후검정 결과:
     Multiple Comparison of Means - Tukey HSD, FWER=0.05
=============================================================
group1 group2  meandiff  p-adj     lower      upper    reject
-------------------------------------------------------------
경기 수원시 경기 평택시 -2722.2102 0.2638  -6156.6212   712.2008  False
경기 수원시 경남 김해시  1886.9776 0.8234  -1732.9291  5506.8842  False
경기 수원시 경남 창원시  2050.6499 0.5124  -1009.0033  5110.3032  False
경기 수원시 경북 구미시   577.4172 0.9999  -2624.9768  3779.8111  False
경기 수원시 경북 포항시 -2105.3496  0.737     -5812.1  1601.4008  False
경기 수원시 서울 강남구  5818.5068 0.0653    -171.525 11808.5386  False
경기 수원시 서울 마포구  1493.3436 0.9857  -2841.6851  5828.3723  False
경기 수원시 제주 제주시   633.9757 0.9999  -2666.7789  3934.7304  False
경기 수원시 충북 청주시 -2978.1706 0.0935  -6178.0157   221.6744  False
경기 평택시 경남 김해시  4609.1878 0.0009   1180.4423  8037.9333   True
경기 평택시 경남 창원시  4772.8601    0.0   1941.9504  7603.7699   True
경기 평택시 경북 구미시  3299.6274  0.017     315.017  6284.2377   True
경기 평택시 경북 포항시   616.8606 0.9999  -2903.4477  4137.1689  False
경기 평택시 서울 강남구   8540.717 0.0002    2664.234 14417.2001   True
경기 평택시 서울 마포구  4215.5538 0.0457     38.8271  8392.2804   True
경기 평택시 제주 제주시  3356.1859 0.0209    266.2744  6446.0974   True
경기 평택시 충북 청주시  -255.9604    1.0  -3237.8357  2725.9148  False
경남 김해시 경남 창원시   163.6724    1.0  -2889.6201  3216.9648  False
경남 김해시 경북 구미시 -1309.5604 0.9546  -4505.8776  1886.7568  False
경남 김해시 경북 포항시 -3992.3272 0.0227  -7693.8289  -290.8254   True
경남 김해시 서울 강남구  3931.5293  0.543   -2055.256  9918.3145  False
경남 김해시 서울 마포구   -393.634    1.0  -4724.1755  3936.9076  False
경남 김해시 제주 제주시 -1253.0018  0.972  -4547.8611  2041.8575  False
경남 김해시 충북 청주시 -4865.1482 0.0001  -8058.9116 -1671.3848   True
경남 창원시 경북 구미시 -1473.2328 0.7145  -4017.6773  1071.2118  False
경남 창원시 경북 포항시 -4155.9995 0.0013  -7311.7672 -1000.2319   True
경남 창원시 서울 강남구  3767.8569 0.5241  -1897.7721  9433.4859  False
경남 창원시 서울 마포구  -557.3063    1.0   -4431.754  3317.1413  False
경남 창원시 제주 제주시 -1416.6742 0.8065  -4083.8548  1250.5063  False
경남 창원시 충북 청주시 -5028.8206    0.0  -7570.0563 -2487.5849   True
경북 구미시 경북 포항시 -2682.7668 0.2286  -5977.1132   611.5796  False
경북 구미시 서울 강남구  5241.0896 0.1091   -502.8812 10985.0605  False
경북 구미시 서울 마포구   915.9264 0.9993  -3072.2052   4904.058  False
경북 구미시 제주 제주시    56.5585    1.0  -2773.2296  2886.3467  False
경북 구미시 충북 청주시 -3555.5878 0.0014  -6266.9948  -844.1808   True
경북 포항시 서울 강남구  7923.8564 0.0014    1884.165 13963.5479   True
경북 포항시 서울 마포구  3598.6932 0.2241   -804.6992  8002.0856  False
경북 포항시 제주 제주시  2739.3253 0.2385   -650.7149  6129.3655  False
경북 포항시 충북 청주시   -872.821  0.998  -4164.6897  2419.0476  False
서울 강남구 서울 마포구 -4325.1632 0.5103 -10769.5676  2119.2411  False
서울 강남구 제주 제주시 -5184.5311 0.1268 -10983.9151   614.8529  False
서울 강남구 충북 청주시 -8796.6775 0.0001 -14539.2276 -3054.1273   True
서울 마포구 제주 제주시  -859.3679 0.9997  -4926.9037  3208.1679  False
서울 마포구 충북 청주시 -4471.5142 0.0142  -8457.5993  -485.4291   True
제주 제주시 충북 청주시 -3612.1464 0.0022  -6439.0496  -785.2431   True
-------------------------------------------------------------

In [14]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd
# Tukey's HSD 사후검정 수행
# `pairwise_tukeyhsd`는 단일 범주형 변수에 대해 수행
# 이를 위해 'amount'를 'region'별로 구분하여 분석

tukey = pairwise_tukeyhsd(endog=data['amount'], groups=data['type_of_business'], alpha=0.05)

# Tukey's HSD 결과 출력
print("\nTukey's HSD 사후검정 결과:")
print(tukey)

c:\Users\OPERATOR-70\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\integrate\_quadpack_py.py:1233: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,

Tukey's HSD 사후검정 결과:
                      Multiple Comparison of Means - Tukey HSD, FWER=0.05
================================================================================================
         group1                  group2           meandiff  p-adj     lower      upper    reject
------------------------------------------------------------------------------------------------
                 기타 주점업                  두발 미용업     97.1954    1.0  -2458.1993  2652.5901  False
                 기타 주점업               비알코올 음료점업  -2832.5192 0.0791  -5814.1571   149.1188  False
                 기타 주점업                서양식 음식점업   1265.0703 0.9756  -2130.3521  4660.4927  False
                 기타 주점업     섬유, 직물 및 의복액세서리 소매업   9594.3068    0.0   5945.5552 13243.0583   True
                 기타 주점업            시계 및 귀금속 소매업  -3775.8435 0.0404  -7469.8748   -81.8121   True
                 기타 주점업       애완용 동물 및 관련용품 소매업   -710.1048 0.9997    -4185.78  2765.5704  False
                 기타 주점업                  의복 소매업   8702.9922    0.0   5702.9087 11703.0758   True
                 기타 주점업 피자, 햄버거, 샌드위치 및 유사 음식점업  -3836.5096 0.0002  -6511.7446 -1161.2747   True
                 기타 주점업                 한식 음식점업     249.519    1.0  -1615.9971  2115.0351  False
                 두발 미용업               비알코올 음료점업  -2929.7146 0.0914  -6068.2597   208.8304  False
                 두발 미용업                서양식 음식점업   1167.8748 0.9894  -2366.1305  4701.8802  False
                 두발 미용업     섬유, 직물 및 의복액세서리 소매업   9497.1113    0.0   5719.0579 13275.1648   True
                 두발 미용업            시계 및 귀금속 소매업  -3873.0389  0.044  -7694.8405   -51.2373   True
                 두발 미용업       애완용 동물 및 관련용품 소매업   -807.3002 0.9995  -4418.4799  2803.8794  False
                 두발 미용업                  의복 소매업   8605.7968    0.0    5449.723 11761.8706   True
                 두발 미용업 피자, 햄버거, 샌드위치 및 유사 음식점업  -3933.7051 0.0005   -6782.772 -1084.6381   True
                 두발 미용업                 한식 음식점업    152.3236    1.0  -1954.9141  2259.5613  False
              비알코올 음료점업                서양식 음식점업   4097.5894 0.0266    244.1084  7951.0705   True
              비알코올 음료점업     섬유, 직물 및 의복액세서리 소매업  12426.8259    0.0    8348.369 16505.2828   True
              비알코올 음료점업            시계 및 귀금속 소매업   -943.3243 0.9994    -5062.34  3175.6914  False
              비알코올 음료점업       애완용 동물 및 관련용품 소매업   2122.4144 0.7892  -1801.9634  6046.7922  False
              비알코올 음료점업                  의복 소매업  11535.5114    0.0    8025.394 15045.6288   True
              비알코올 음료점업 피자, 햄버거, 샌드위치 및 유사 음식점업  -1003.9905 0.9933   -4240.857  2232.8761  False
              비알코올 음료점업                 한식 음식점업   3082.0382 0.0071    474.2473  5689.8291   True
               서양식 음식점업     섬유, 직물 및 의복액세서리 소매업   8329.2365    0.0   3939.1864 12719.2865   True
               서양식 음식점업            시계 및 귀금속 소매업  -5040.9137 0.0118  -9468.6692  -613.1582   True
               서양식 음식점업       애완용 동물 및 관련용품 소매업  -1975.1751 0.9034  -6222.4648  2272.1147  False
               서양식 음식점업                  의복 소매업    7437.922    0.0   3570.1509  11305.693   True
               서양식 음식점업 피자, 햄버거, 샌드위치 및 유사 음식점업  -5101.5799 0.0004  -8723.1864 -1479.9734   True
               서양식 음식점업                 한식 음식점업  -1015.5513 0.9894   -4087.896  2056.7934  False
    섬유, 직물 및 의복액세서리 소매업            시계 및 귀금속 소매업 -13370.1502    0.0   -17995.03 -8745.2704   True
    섬유, 직물 및 의복액세서리 소매업       애완용 동물 및 관련용품 소매업 -10304.4116    0.0 -14756.8226 -5852.0005   True
    섬유, 직물 및 의복액세서리 소매업                  의복 소매업   -891.3145 0.9996  -4983.2758  3200.6468  False
    섬유, 직물 및 의복액세서리 소매업 피자, 햄버거, 샌드위치 및 유사 음식점업 -13430.8164    0.0 -17290.9366 -9570.6962   True
    섬유, 직물 및 의복액세서리 소매업                 한식 음식점업  -9344.7877    0.0 -12694.9812 -5994.5943   True
           시계 및 귀금속 소매업       애완용 동물 및 관련용품 소매업   3065.7387  0.484  -1423.8542  7555.3315  False
           시계 및 귀금속 소매업                  의복 소매업  12478.8357    0.0   8346.4481 16611.2232   True
           시계 및 귀금속 소매업 피자, 햄버거, 샌드위치 및 유사 음식점업    -60.6662    1.0  -3963.6148  3842.2824  False
           시계 및 귀금속 소매업                 한식 음식점업   4025.3625 0.0069    625.9102  7424.8148   True
      애완용 동물 및 관련용품 소매업                  의복 소매업    9413.097    0.0   5474.6865 13351.5076   True
      애완용 동물 및 관련용품 소매업 피자, 햄버거, 샌드위치 및 유사 음식점업  -3126.4048 0.1834  -6823.3575   570.5478  False
      애완용 동물 및 관련용품 소매업                 한식 음식점업    959.6238 0.9943  -2201.1873  4120.4349  False
                 의복 소매업 피자, 햄버거, 샌드위치 및 유사 음식점업 -12539.5019    0.0 -15793.3675 -9285.6362   True
                 의복 소매업                 한식 음식점업  -8453.4732    0.0 -11082.3342 -5824.6123   True
피자, 햄버거, 샌드위치 및 유사 음식점업                 한식 음식점업   4086.0287    0.0   1834.9643   6337.093   True
------------------------------------------------------------------------------------------------

In [15]:
import statsmodels.api as sm
import pandas as pd
from statsmodels.formula.api import ols

# 데이터 불러오기
data = data_sampled[["card_company","region","type_of_business","amount"]]

## Two-way ANOVA에 맞는 수식을 설정하는 코드
two_way_anova = ols('amount ~ C(region) + C(type_of_business) + C(card_company) + \
            C(region):C(type_of_business) + C(region):C(card_company) + \
            C(type_of_business):C(card_company) + C(region):C(type_of_business):C(card_company)'
           , data = data).fit()
 
## 결과 해석을 저장하는 코드
result = sm.stats.anova_lm(two_way_anova)
 
## 결과 요약
print(result)

                                                   df        sum_sq  \
C(region)                                         9.0  2.710745e+10
C(type_of_business)                               9.0  5.024687e+10
C(card_company)                                   7.0  3.413995e+09
C(region):C(type_of_business)                    81.0  1.100326e+11
C(region):C(card_company)                        63.0  1.544219e+10
C(type_of_business):C(card_company)              63.0  1.551570e+10
C(region):C(type_of_business):C(card_company)   567.0  6.952516e+10
Residual                                       5943.0  1.067018e+12

                                                    mean_sq          F  \
C(region)                                      3.011939e+09  16.775681
C(type_of_business)                            5.582985e+09  31.095707
C(card_company)                                4.877136e+08   2.716431
C(region):C(type_of_business)                  1.358428e+09   7.566072
C(region):C(card_company)                      2.451142e+08   1.365219
C(type_of_business):C(card_company)            2.462809e+08   1.371717
C(region):C(type_of_business):C(card_company)  1.226193e+08   0.682956
Residual                                       1.795420e+08        NaN

                                                     PR(>F)
C(region)                                      1.302313e-27
C(type_of_business)                            1.008191e-53
C(card_company)                                8.210402e-03
C(region):C(type_of_business)                  8.661573e-78
C(region):C(card_company)                      2.953809e-02
C(type_of_business):C(card_company)            2.761674e-02
C(region):C(type_of_business):C(card_company)  1.000000e+00
Residual                                                NaN

In [16]:
result

,df,sum_sq,mean_sq,F,PR(>F)
C(region),9.0,2.710745e+10,3.011939e+09,16.775681,1.302313e-27
C(type_of_business),9.0,5.024687e+10,5.582985e+09,31.095707,1.008191e-53
C(card_company),7.0,3.413995e+09,4.877136e+08,2.716431,8.210402e-03
C(region):C(type_of_business),81.0,1.100326e+11,1.358428e+09,7.566072,8.661573e-78
C(region):C(card_company),63.0,1.544219e+10,2.451142e+08,1.365219,2.953809e-02
C(type_of_business):C(card_company),63.0,1.551570e+10,2.462809e+08,1.371717,2.761674e-02
C(region):C(type_of_business):C(card_company),567.0,6.952516e+10,1.226193e+08,0.682956,1.000000e+00
Residual,5943.0,1.067018e+12,1.795420e+08,NaN,NaN